### ISSUE TITLE
Creating DhcpOptions ?

### ISSUE THREAD

**Issue by rgrunbla** [bluecatengineering/dhcproto#16]
Hello,

It seems right now, the dhcproto does not provide any way to create DhcpOption such as IAAddr, or IANA, from scratch. Structures have private fields, and no getter / setter / new methods. I fixed that in a fork by setting all the structure fields to public ( https://github.com/rgrunbla/dhcproto/commit/3ac5f0419d97acfd64360aa9603e09fcb8cbc4ac ) but that might not be what you want for this crate. Could this be solved upstream ?

Thanks,
Rémy

**Comment by stappersg** [comment]
On Wed, Jan 05, 2022 at 07:24:29AM -0800, Rémy Grünblatt wrote:
>  ... I fixed that in a fork by setting all the structure fields to public ( https://github.com/rgrunbla/dhcproto/commit/3ac5f0419d97acfd64360aa9603e09fcb8cbc4ac ) but that might not be what you want for this crate.

In which `git branch` has that commit?

**Comment by rgrunbla** [comment]
In the pub_struct branch: https://github.com/rgrunbla/dhcproto/tree/pub_struct

**Comment by leshow** [comment]
Ah! Thanks for filing. It is an oversight, I have not had a chance to use dhcpv6 much yet so there may be some stuff like this missing. I think there might be some option fields we might not want to commit making `pub` just yet, but I'll take a closer look.
