### ISSUE TITLE
Does DHCP guarantee source host names are UTF-8?

### ISSUE THREAD

**Issue by saethlin** [bluecatengineering/dhcproto#3]
This crate assumes the `sname` field of a `v4::Message` will be sent as UTF-8, but as far as I can tell in the RFC there is no mention at all of encoding. In addition, the pre-ipv6 RFCs for DHCP predate the UTF-8 RFC.

Perhaps most importantly, there is no encoding requirement for domain names in DNS, so I'd be a little surprised if that non-requirement doesn't extend to DHCP. This might sound a bit pedantic, but I'm aware of an organization that stores binary data in domain names within DNS, and a quick Google turned up this person who found Windows encoding in DHCP: https://stackoverflow.com/questions/31215085/windows-dhcp-client-hostname-encoding

Can the UTF-8 assumption/requirement in this crate be lifted?

**Comment by leshow** [comment]
Thanks for bringing this up. I remember waffling between a few different types at first before looking at other another languages implementation that used a string type and just going with that. But you're absolutely right that I don't think we can enforce UTF-8 and still be 'correct'. I suppose just a slice of bytes would be the safest bet? I'd like to do a bit of hunting again before I commit to changing the API though. Let me know what you think.

**Comment by saethlin** [comment]
I would return `Vec<u8>` or `&[u8]` (because the bytes are in the right shape in the packet), and leave a comment in the docs that DHCP doesn't require any particular encoding.

**Comment by stappersg** [comment]
On Thu, Sep 16, 2021 at 06:33:52AM -0700, Ben Kimock wrote:
> I would return `Vec<u8>` or `&[u8]` (because the bytes are in the
> right shape in the packet),

Yes


> and leave a comment in the docs
> that DHCP doesn't require any particular encoding.

Please avoid that.

DHCP happens at transport level, not at presentation level.


Regards
Stappers

**Comment by saethlin** [comment]
> Please avoid that.

Hunh? What's wrong with putting something in the docs?

**Comment by leshow** [comment]
> DHCP happens at transport level, not at presentation level

DHCP is an application protocol? Though it has some information from the transport layer, like `chaddr`. At least, wikipedia seems to think so https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol

I also am not sure I understand your concern with documenting the type of `sname`.

**Comment by stappersg** [comment]
On Thu, Sep 16, 2021 at 11:29:55AM -0700, Evan Cameron wrote:
> 
> I also am not sure I understand your concern
> with documenting the type of `sname`. 
> 

Character encoding is a can of worms better left closed.


I think we, DHCProto people, should just stick to bytes.
We already agree to avoid UTF-8 in DHCP packets.


Regards
Stappers

**Comment by leshow** [comment]
All we're talking about is explaining that there is no particular encoding to the bytes, so I think this is in agreement with what you're saying.

**Comment by stappersg** [comment]
On Thu, Sep 16, 2021 at 07:19:58PM -0700, Evan Cameron wrote:
> All we're talking about is explaining that there is no particular
> encoding to the bytes, so I think this is in agreement with what
> you're saying.


Acknowledge
