### ISSUE TITLE
v6 HType

### ISSUE THREAD

**Issue by leshow** [bluecatengineering/dhcproto#68]
Our DUID impl for v6 uses the v4 HType which is a u8, for v6 it is meant to be a u16. Let's create a new HType for v6 and change the DUID impl to use it

https://github.com/bluecatengineering/dhcproto/blob/master/src/v6/duid.rs#L16

**Comment by chenwanqq** [comment]
I'm working on this thing! I found some definitions in https://www.iana.org/assignments/arp-parameters/arp-parameters.xhtml
that you did not define in the v4 Htype, is there any other consideration? Do you need to supplement it completely in this update?

**Comment by leshow** [comment]
closed in #69

**Comment by leshow** [comment]
In the future, put "closes #number" at the top of your PR comment so these issues close automatically

**Comment by stappersg** [comment]
On Tue, Nov 28, 2023 at 09:35:05AM -0800, Evan Cameron wrote:
> In the future, put "closes #number" at the top of your PR comment
> so these issues close automatically

For the better vendor-lock-in  into  "git hub".
